"""update product transfer table

Revision ID: 397e506804bf
Revises: 00fd8b9b3c7a
Create Date: 2026-08-04 14:40:32.373087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '397e506804bf'
down_revision: Union[str, Sequence[str], None] = '00fd8b9b3c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_transfers_ibfk_2'), 'product_transfers', type_='foreignkey')
    op.drop_column('product_transfers', 'qty')
    op.drop_column('product_transfers', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_transfers', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_transfers', sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('product_transfers_ibfk_2'), 'product_transfers', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
