"""update product table delete supplier

Revision ID: 7ecbdc70df72
Revises: 335f7d063d4f
Create Date: 2026-08-29 14:42:02.906721

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ecbdc70df72'
down_revision: Union[str, Sequence[str], None] = '335f7d063d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_ibfk_3'), 'product', type_='foreignkey')
    op.drop_column('product', 'supplier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('supplier_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('product_ibfk_3'), 'product', 'supplier', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
