"""update product int to decimal

Revision ID: e048075493fd
Revises: 7ecbdc70df72
Create Date: 2026-08-29 15:50:13.627718

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e048075493fd'
down_revision: Union[str, Sequence[str], None] = '7ecbdc70df72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'cost_price',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('product', 'sale_price',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'sale_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('product', 'cost_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
