"""change payment_method to string

Revision ID: ff6695df6e14
Revises: 0b76abb3b310
Create Date: 2026-07-08 09:56:12.928569

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff6695df6e14'
down_revision: Union[str, Sequence[str], None] = '0b76abb3b310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_payments', 'payment_method',
               existing_type=mysql.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_payments', 'payment_method',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
