"""remove qty and allow_insert_qty from product

Revision ID: 23880e20ce91
Revises: 3023b3a13055
Create Date: 2026-07-14 18:45:14.118226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '23880e20ce91'
down_revision: Union[str, Sequence[str], None] = '3023b3a13055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'qty')
    op.drop_column('product', 'allow_insert_qty')
    op.add_column('purchases', sa.Column('warehouse_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchases', 'warehouses', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'warehouse_id')
    op.add_column('product', sa.Column('allow_insert_qty', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
