"""add new fields

Revision ID: 3023b3a13055
Revises: ff6695df6e14
Create Date: 2026-07-11 08:49:11.258566

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3023b3a13055'
down_revision: Union[str, Sequence[str], None] = 'ff6695df6e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('product_transfers', sa.Column('reference_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('supplier', sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.add_column('warehouses', sa.Column('reference_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('warehouses', sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'note')
    op.drop_column('warehouses', 'reference_no')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'photo')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'role_id')
    op.drop_column('supplier', 'photo')
    op.drop_column('product_transfers', 'reference_no')
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
